// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9f6r-YLOa9mJdxhquRVDxbX9jSZXqt90',
    appId: '1:270432106244:web:6c2504d6a24f3db6f98251',
    messagingSenderId: '270432106244',
    projectId: 'flutter-chat-app-423ce',
    authDomain: 'flutter-chat-app-423ce.firebaseapp.com',
    storageBucket: 'flutter-chat-app-423ce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-iF0jOxbbdugfqrTyzLRIws9X2-WWaxg',
    appId: '1:270432106244:android:368006bc98fb440af98251',
    messagingSenderId: '270432106244',
    projectId: 'flutter-chat-app-423ce',
    storageBucket: 'flutter-chat-app-423ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoMlhAGs2hI8-xipSAbmWv1JVjedDVasE',
    appId: '1:270432106244:ios:86e9381aabee5127f98251',
    messagingSenderId: '270432106244',
    projectId: 'flutter-chat-app-423ce',
    storageBucket: 'flutter-chat-app-423ce.firebasestorage.app',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoMlhAGs2hI8-xipSAbmWv1JVjedDVasE',
    appId: '1:270432106244:ios:86e9381aabee5127f98251',
    messagingSenderId: '270432106244',
    projectId: 'flutter-chat-app-423ce',
    storageBucket: 'flutter-chat-app-423ce.firebasestorage.app',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9f6r-YLOa9mJdxhquRVDxbX9jSZXqt90',
    appId: '1:270432106244:web:bf431bd332813812f98251',
    messagingSenderId: '270432106244',
    projectId: 'flutter-chat-app-423ce',
    authDomain: 'flutter-chat-app-423ce.firebaseapp.com',
    storageBucket: 'flutter-chat-app-423ce.firebasestorage.app',
  );

}